### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by n0madic**

### CODE REVIEW

**Comment by rdotter** [comment]
@MartinNowak we were looking for a Kafka docker container for Gitlab CI and it looks like yours will do fine :-)

Can you merge this above request? We also need version 1.1.0 for Kafka.

Thanks!

**Comment by MartinNowak** [comment]
Yes @rdotter, have missed that PR.

**Comment by rdotter** [comment]
@MartinNowak thanks ! :-) is it possible you create a new tag so it can be used via https://hub.docker.com/r/martinnowak/docker-kafka/tags?

**Comment by MartinNowak** [comment]
Yes, new 1.1 image is available.
Also fixed a few smaller changes @rdotter.

**Pull request merged**
